### PR TITLE
Minor Changes

### PR DESCRIPTION
**Pull request by LucaFerraro03**
Fixed some minor errors in the code

### CODE REVIEW

**Comment by nbicocchi** [comment]
OK

**Comment by nbicocchi** [comment]
There are still some minor issues in the GUI, if you like to discuss them a bit.

**Comment by LucaFerraro03** [comment]
I'm sorry I couldn't reply earlier but I was busy studying, could you please point out those issues so me and my collegue can solve them?

**Comment by nbicocchi** [comment]
Hello, I checked again and the font issue originates on my machine. Do not worry about it.

**Pull request merged**
