### PR TITLE
Manuel and Mattia's project: camera

### PR DESCRIPTION
**Pull request by M61ss**
I thought to create a page about how to create multiple scene in the same application because it is very common that someone in his project needs to create a new window, which could be different from a DialogPane (that I saw that it is already shown in address book), maybe more general. I added also alerts because they are frequently used.

Do you think that it could be a nice idea? If there are errors or shortcomings I can fix those.

### CODE REVIEW

**Comment by nbicocchi** [comment]
It is nice and well organized. However it does not fit well in that series because it is not related to the address book example. I believe the best way to propose it is building a small maven project using those concepts and attaching the readme to it. It could be your home project for example. We can talk about this in class eventually.

**Comment by M61ss** [comment]
It is a nice purpose, but I am already developing another project (a webcam, fi you remember) with my teammate. If you agree, I could try to create a simple educational project as you asked me, I like so much to code. Anyway, I promise nothing because I have to prepare other exams.

**Comment by nbicocchi** [comment]
There are 2 options: (1) include some windowing into your webcam project and add the slides to its readme, (2) write another very small educational project only for showing what you discuss in the slides

**Comment by M61ss** [comment]
Ok interesting, I am going to discuss about that this afternoon with my teammate. In our project we use all window types which I shown into the slide, so using this one makes sense. Anyway, I need to talk about this option with my teammate. We will communicate you our decision soon.

**Comment by M61ss** [comment]
I talked with my teammate and it agrees to implement all into our project (the webcam). When we will finish to develop, I will push all on this pull request.

**Comment by M61ss** [comment]
We finished our project, it's ok? We will update and attach to it the slide.

**Comment by M61ss** [comment]
We finished the slide

**Comment by nbicocchi** [comment]
I integrated manually under simple-webcam. It's OK. The filters combo box is still debatable.

**Pull request closed without merging**
